### ISSUE TITLE
Unable to perform `meteor bundle`

### ISSUE THREAD

**Issue by evandrix** [bmelton/Orbvt#3]
The following error message is displayed:

```
Errors prevented bundling:
Exception while bundling application:
Error: Attributes on <body> not supported - line 26, file /Users/evandrix/Downloads/Orbvt/orbvt.html
</body>
    at /usr/local/meteor/packages/templating/html_scanner.js:23:14
    at Object._handleTag (/usr/local/meteor/packages/templating/html_scanner.js:147:15)
    at Object.scan (/usr/local/meteor/packages/templating/html_scanner.js:97:20)
    at /usr/local/meteor/packages/templating/package.js:46:32
    at [object Object].add_file (/usr/local/meteor/app/lib/bundler.js:196:5)
    at /usr/local/meteor/app/lib/bundler.js:97:16
    at Array.forEach (native)
    at Function.<anonymous> (/usr/local/meteor/app/lib/third/underscore.js:76:11)
    at /usr/local/meteor/app/lib/bundler.js:96:11
    at Array.forEach (native)
```

Upon further investigation, it turns out the following line of code is offending to meteor:

```
<body class="posts index">
```

...in particular, the "class" attribute in the body tag

Have already tried running `meteor update` - to version v0.4.0

**Comment by evandrix** [comment]
Moved on and not using Meteor anymore for any serious work, so closing issue.
